config/routes.rb
Rails.application.routes.draw do

  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, :email, :password, presence:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new


  end

  def create
    @user = User.new(name: params[:name], email: params[:email], password: params[:password])
    # puts(params)

    if @user.save
      redirect_to new_user_path, notice: "User created"
    else
      render :new, status: :unprocessable_entity
    end

  end

  def edit
    @user = User.find(params[:id])
  end

  def update
   @user = User.find(params[:id])
   puts "Userrerrrrrrrrrrrr"


   if @user.update(user_params)
    redirect_to new_user_path, notice: "User updated"
  else
    render :edit, status: :unprocessable_entity
  end

  end

  private

  def user_params
   params.require(:user).permit(:name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReFormer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>



<%= form_with model: @user do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :email, 'Enter Email' %><br>
    <%= form.text_field :email %>
  </p>

   <p>
    <%= form.label :password %><br>
    <%= form.text_field :password %>
  </p>
 
 
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/users/new.html.erb
<!--
<form action="/users" method="POST">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="name">Name:</label>
  <input type="text" id="name" name="user[name]"><br><br>
  <label for="email">Email:</label>
  <input type="text" id="email" name="user[email]"><br><br>
  <label for="lname">Password:</label>
  <input type="text" id="password" name="user[password]"><br><br>
  <input type="submit" value="Submit">
</form>
-->

<!--

<%= form_tag("/users", method: "post") do %>
  <%= label_tag(:name, "Name:") %>
  <%= text_field_tag(:name) %>
  <%= label_tag(:email, "Email:") %>
  <%= email_field_tag(:email) %>
  <%= label_tag(:password, "Password:") %>
  <%= password_field_tag(:password) %>
  <%= submit_tag("Submit") %>
<% end %>
-->


<%= form_with url: users_path do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :email, 'Enter Email' %><br>
    <%= form.text_field :email %>
  </p>

   <p>
    <%= form.label :password %><br>
    <%= form.text_field :password %>
  </p>
 
 
  <p>
    <%= form.submit %>
  </p>
<% end %>